"""
Report Generation – PDF (ReportLab/FPDF2) & Excel (openpyxl) exports
"""

import os
import io
from datetime import datetime
from flask import current_app


# ── PDF ──────────────────────────────────────────────────────────────────────
def generate_pdf_report(detection_data: dict, result_image_path: str = None) -> bytes:
    """Generate a PDF report and return as bytes."""
    try:
        from fpdf import FPDF
    except ImportError:
        raise RuntimeError("fpdf2 not installed. Run: pip install fpdf2")

    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Header
    pdf.set_fill_color(21, 101, 192)
    pdf.rect(0, 0, 210, 40, "F")
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_xy(10, 10)
    pdf.cell(190, 12, "RoadGuard AI - Detection Report", align="C")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_xy(10, 24)
    pdf.cell(190, 8, "AI-Based Road Quality Monitoring System", align="C")
    pdf.ln(30)

    # Condition badge
    condition = detection_data.get("road_condition", "Unknown")
    severity  = detection_data.get("severity",       "Unknown")
    colors    = {"Good":(40,167,69),"Moderate":(255,193,7),"Poor":(253,126,20),"Critical":(220,53,69)}
    r, g, b   = colors.get(condition, (108,117,125))
    pdf.set_fill_color(r, g, b)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(190, 10, f"Road Condition: {condition}  |  Severity: {severity}", align="C", fill=True)
    pdf.ln(8)

    # Details
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(190, 8, "Detection Details", border="B")
    pdf.ln(6)

    rows = [
        ("Date & Time",    datetime.now().strftime("%Y-%m-%d %H:%M:%S")),
        ("Damage Types",   ", ".join(detection_data.get("damage_types", [])) or "None"),
        ("Avg Confidence", f"{detection_data.get('avg_confidence',0)*100:.1f}%"),
        ("Detections",     str(detection_data.get("detection_count", 0))),
        ("Pred. Time",     f"{detection_data.get('prediction_time',0):.3f}s"),
        ("Latitude",       str(detection_data.get("latitude", "N/A"))),
        ("Longitude",      str(detection_data.get("longitude","N/A"))),
        ("Location",       detection_data.get("location_name","N/A")),
        ("Maps Link",      detection_data.get("maps_link","N/A")),
    ]

    pdf.set_font("Helvetica", "", 10)
    for label, value in rows:
        pdf.set_fill_color(245, 245, 245)
        pdf.cell(60, 8, label, border=1, fill=True)
        pdf.cell(130, 8, str(value)[:80], border=1)
        pdf.ln()

    # Embed result image if available
    if result_image_path and os.path.exists(result_image_path):
        pdf.ln(6)
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(190, 8, "AI Detection Result", border="B")
        pdf.ln(4)
        try:
            pdf.image(result_image_path, w=180)
        except Exception:
            pass

    # Footer
    pdf.set_y(-20)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(128, 128, 128)
    pdf.cell(190, 6,
             f"Generated by RoadGuard AI on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
             align="C")

    return bytes(pdf.output())


# ── Excel ─────────────────────────────────────────────────────────────────────
def generate_excel_report(detections: list) -> bytes:
    """Generate an Excel workbook from a list of Detection ORM objects."""
    try:
        import openpyxl
        from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
        from openpyxl.utils  import get_column_letter
    except ImportError:
        raise RuntimeError("openpyxl not installed. Run: pip install openpyxl")

    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "RoadGuard Detections"

    header_font  = Font(bold=True, color="FFFFFF", size=11)
    header_fill  = PatternFill("solid", fgColor="1565C0")
    center_align = Alignment(horizontal="center", vertical="center")
    thin_border  = Border(
        left  =Side(style="thin"),
        right =Side(style="thin"),
        top   =Side(style="thin"),
        bottom=Side(style="thin"),
    )

    headers = [
        "ID","Date","Time","Road Condition","Severity","Damage Types",
        "Avg Confidence (%)","Detection Count","Pred. Time (s)",
        "Latitude","Longitude","Location","Maps Link","Email Sent","Source",
    ]

    # Header row
    for col, h in enumerate(headers, 1):
        cell = ws.cell(row=1, column=col, value=h)
        cell.font      = header_font
        cell.fill      = header_fill
        cell.alignment = center_align
        cell.border    = thin_border
        ws.column_dimensions[get_column_letter(col)].width = max(len(h) + 4, 15)

    # Data rows
    alt_fill = PatternFill("solid", fgColor="E3F2FD")
    for row_idx, det in enumerate(detections, 2):
        fill = alt_fill if row_idx % 2 == 0 else PatternFill()
        values = [
            det.id,
            det.timestamp.strftime("%Y-%m-%d") if det.timestamp else "",
            det.timestamp.strftime("%H:%M:%S") if det.timestamp else "",
            det.road_condition or "",
            det.severity or "",
            ", ".join(det.get_damage_types()),
            round(det.avg_confidence * 100, 1),
            det.detection_count or 0,
            round(det.prediction_time or 0, 3),
            det.latitude or "",
            det.longitude or "",
            det.location_name or "",
            det.maps_link or "",
            "Yes" if det.email_sent else "No",
            det.source or "image",
        ]
        for col, val in enumerate(values, 1):
            cell = ws.cell(row=row_idx, column=col, value=val)
            cell.fill      = fill
            cell.alignment = center_align
            cell.border    = thin_border

    # Auto-filter
    ws.auto_filter.ref = f"A1:{get_column_letter(len(headers))}1"
    ws.freeze_panes   = "A2"

    output = io.BytesIO()
    wb.save(output)
    return output.getvalue()


# ── CSV ───────────────────────────────────────────────────────────────────────
def generate_csv_report(detections: list) -> str:
    """Return a CSV string from Detection ORM objects."""
    import csv, io
    output = io.StringIO()
    writer = csv.writer(output)

    writer.writerow([
        "ID","Date","Time","Road Condition","Severity","Damage Types",
        "Avg Confidence (%)","Detection Count","Latitude","Longitude",
        "Location","Maps Link","Email Sent","Source",
    ])
    for det in detections:
        writer.writerow([
            det.id,
            det.timestamp.strftime("%Y-%m-%d") if det.timestamp else "",
            det.timestamp.strftime("%H:%M:%S") if det.timestamp else "",
            det.road_condition or "",
            det.severity or "",
            "|".join(det.get_damage_types()),
            round(det.avg_confidence * 100, 1),
            det.detection_count or 0,
            det.latitude or "",
            det.longitude or "",
            det.location_name or "",
            det.maps_link or "",
            "Yes" if det.email_sent else "No",
            det.source or "image",
        ])
    return output.getvalue()
